### ISSUE TITLE
Grab Weiyu's former codes into the tip WAM development for the NetCDF output of WAM-IPE interface variables

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM#10]
Doing efforts to manually grab Weiyu's former codes (several subroutines in NEMS/src/atmos/gsm/dyn) into the current WAM develop version code for the NetCDF output of several very helpful WAM-IPE interface variables (total number density, mean mass...). The validation idea for Weiyu's codes is that we would like to get the bit by bit regular WAM sig output between the tip WAM version and the one after adding his codes.  
The reference former issue is NOAA-SWPC/WAM-IPE#134.

**Comment by akubaryk** [comment]
@ZhuxiaoLi66 please take a look at the following NetCDF file, created from the latest updates to the netcdf_output WAM branch: /scratch1/NCEPDEV/stmp4/Adam.Kubaryk/ncout_test/wam_fields.nc

It's worth noting that it adds about ~8.5 seconds to the model run per write (3 hour run with hourly writes went from 1m22s to 1m47s), and give or take 170MB per write (compared to 19MB for a history file). Since these are not intended as model history files and are only being used for diagnostic purposes, we could use NetCDF's built-in compression options to cut down the file size, but having never used this option before, I don't know what kind of potential disk savings or additional processing time there might be. We also might consider simply writing fewer history files when this option is turned on, though that's not going to make much of a difference.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk got the file and your information. going to take a look at the NetCDF file. Thanks and talk later.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk thanks for adding the Netcdf output option to WAM. I checked the variables in the wam_fields.nc, they looks pretty reasonable (I proposed the units of the variables, would like to confirm with you here). 
For T, U, V,
![TUV_netcdf_out_test](https://user-images.githubusercontent.com/22546571/70651386-99b1a280-1c48-11ea-91db-cac35a5633d3.png)

For number density of O, O2, N2, I supposed that the units are (1/m3) here, then we can explain the magnitude difference between WAM and MSIS (not the same date comparison, not necessary have same pattern, while we can see the pattern are quite similar.)
   
![number_den_netcdf_out_test](https://user-images.githubusercontent.com/22546571/70651433-b3eb8080-1c48-11ea-8736-3c5b5092e8ac.png)

**Comment by ZhuxiaoLi66** [comment]
As for the extra time and disk space needed by the NetCDF writing, my thought is that since the NetCDF output is only an option (not the routine output for operational) for WAM run, maybe we don't need to worry too much about the disk resource.  The sig output need to be transformed into NetCDF format for all the diagnostic runs anyway. As for the compression method on NetCDF, we can try it, I don't know how the coupling (WAM-IPE) run handle this for its NetCDF output?

**Comment by ZhuxiaoLi66** [comment]
Adam, excuse me to ask the following question (do hope it is not a heart-attack one). 
Do you think it is facile to add the possibility to do the every min or 3 mins NetCDF output for WAM? just like you did for Joule Heating integral output?
we don't always do the very timestep output, while sometimes for the storm runs especially for the satellite validation, we need it. what is your thought about this? 
Thanks very much for the already very great and hard work!!!

**Comment by akubaryk** [comment]
Here are the new units:
```
	float w(time, levs, lat, lon) ;
		w:units = "m/s" ;
	float z(time, levs, lat, lon) ;
		z:units = "m" ;
	float u(time, levs, lat, lon) ;
		u:units = "m/s" ;
	float v(time, levs, lat, lon) ;
		v:units = "m/s" ;
	float t(time, levs, lat, lon) ;
		t:units = "K" ;
	float q1(time, levs, lat, lon) ;
		q1:units = "kg/kg" ;
	float q2(time, levs, lat, lon) ;
		q2:units = "kg/kg" ;
	float q3(time, levs, lat, lon) ;
		q3:units = "kg/kg" ;
	float q4(time, levs, lat, lon) ;
		q4:units = "m^-3" ;
	float q5(time, levs, lat, lon) ;
		q5:units = "m^-3" ;
	float n2(time, levs, lat, lon) ;
		n2:units = "m^-3" ;
	float dn(time, levs, lat, lon) ;
		dn:units = "kg*m^-3" ;
	float gm(time, levs, lat, lon) ;
		gm:units = "kg/mol" ;
```
For compression, it turns out that approach is *extremely* effective. Not only were the three hourly outputs compressed to 2.2MB (~200x compression), but the wallclock dropped back to the 1m25s range; seems most of the time spent was on I/O, which isn't so surprising in retrospect. You can check the outputs here: `/scratch1/NCEPDEV/stmp4/Adam.Kubaryk/compress_ncout_test/wam_fields.nc` -- but I think you'll find it's very similar to the last set (with the units added). It makes me wonder if we can't utilize this in the IPE repo for smaller diagnostic files with faster writes as well -- although it should be noted that you can't use compression with parallel writes (another argument for asynchronous I/O in IPE).

It is possible to output at every timestep -- should be as simple as setting fhout_nc=0. With the above information, it shouldn't really be a big deal to run for a relatively long time with every-timestep output; up to an extra minute per model hour on wallclock, 45MB/hour of data storage or roughly 1GB/day is extremely tolerable.

I'll wait for your comment on the above units and then commit up these changes.

**Comment by ZhuxiaoLi66** [comment]
Great to know!! have to do something else now, will double check the units after an hour, seems fine to me though!

**Comment by ZhuxiaoLi66** [comment]
All the units are correct!

**Comment by ZhuxiaoLi66** [comment]
While when I apply ncview or NCL to display the compressed wam_fields.nc directly, it seems that only the surface level has valid values for ncview, doesn't have any for NCL. I bet we need to do the decompression before use it?

**Comment by akubaryk** [comment]
Well that makes a lot more sense for the file size and speed, oops.

**Comment by akubaryk** [comment]
So with the full field being written, ~75MB/write and with the added time on the compression, it's more like ~10s/cycle (in one single test). So it's 110GB/day and ~4 hours/day wallclock with every-timestep output, not quite as appealing anymore.

It's true that this time comes out of the post-processing, but this diagnostic work is also being done with 39 idle cores rather than in parallel. Kind of indifferent on the best path forward.

**Comment by akubaryk** [comment]
One option would be an additional namelist parameter by which the user can select which fields they want, e.g.
```
#         w, z, u, v, t,q1,q2,q3,q4,q5,n2,den,gmol
nc_fields=F, F, T, T, T, F, F, F, T, F, T, F, F
```
for U, V, T, O, N2 only? I'm sure there's a better way to do this, but this would work...

**Comment by ZhuxiaoLi66** [comment]
I think it is a good idea to use the 'nc_fields'. can we also output every 3 mins or 6 mins instead of every 1 min (time step length)?

**Comment by ZhuxiaoLi66** [comment]
so there is no makeup way for the compression method?

**Comment by akubaryk** [comment]
We can leave the compression method in, just a matter of trading compute time for disk space. Can even make that a namelist parameter, too. NetCDF4 (or HDF5 beneath it) supports compression levels 1-9 -- 0 can simply not enable it?

For the output, I can change FHOUT_NC to something like DELOUT_NC, where that would be the same unit as DELTIM (seconds) -- e.g. 60 for every timestep, 180 for every three, 3600 for every hour, etc.

**Comment by ZhuxiaoLi66** [comment]
As long as we can get the valid NetCDF files, something like https://www.unidata.ucar.edu/blogs/developer/entry/netcdf_compression ?
not sure it is the same method? seems the file size don't reduced dramatically (~200 x) after the compression. 

The 'DELOUT_NC', looks totally fine for me.

**Comment by ZhuxiaoLi66** [comment]
Adam, could you please change the variable names q1, q2, q3, q4, q5 into qr, Oz, clw, O, O2 if not very complicated? thanks.

**Comment by akubaryk** [comment]
Sure thing.

**Comment by akubaryk** [comment]
WAM branch netcdf_output has been updated and GSMWAM-IPE branch wam_netcdf_output also updated.

**Comment by ZhuxiaoLi66** [comment]
Got it, thanks for the great job!

**Comment by akubaryk** [comment]
Pulls are open for this. wam_fields.nc is now linked into the ROTDIR with the cycle appended for restart-enabled output.
